### PR TITLE
Define some of the cluster resource names

### PR DESCRIPTION
**Pull request by mpagot**
Centralize name composition for some of the cluster resources

Ticket : https://jira.suse.com/browse/TEAM-9085

# Verification

#### sle-15-SP5-HanaSr-Azure-Byos-x86_64-Build15-SP5_2024-02-23T05:03:08Z-hanasr_azure_test_spn@64bit 
-  http://openqaworker15.qa.suse.cz/tests/276652 :red_circle: two consecutive Ansible reboot timeout.
-  http://openqaworker15.qa.suse.cz/tests/276655

 #### sle-15-SP5-HanaSr-Azure-Byos-x86_64-Build15-SP5_2024-02-23T05:03:08Z-hanasr_azure_test_sbd@64bit

- http://openqaworker15.qa.suse.cz/tests/276653 :green_circle: 

#### sle-15-SP5-HanaSr-Azure-Byos-x86_64-Build15-SP5_2024-02-23T05:03:08Z-hanasr_azure_test_msi@64bit 

- http://openqaworker15.qa.suse.cz/tests/276654 :red_circle: failure is later during the test, it is "SSH connection refused"

#### sle-15-SP6-Qesap-Azure-Byos-Ibs-x86_64-BuildLATEST_AZURE_SLE15_6_BYOS_IBS-qesap_azure_uri@az_Standard_E8s_v3 

- http://openqaworker15.qa.suse.cz/tests/276651 :green_circle: 

#### sle-15-SP5-Qesap-Azure-Byos-x86_64-BuildLATEST_AZURE_SLE15_5_BYOS-qesap_azure_sapconf_test@64bit 

- http://openqaworker15.qa.suse.cz/tests/276649 :green_circle: 

#### sle-15-SP5-Qesap-Azure-Byos-x86_64-BuildLATEST_AZURE_SLE15_5_BYOS-qesap_azure_saptune_test@64bit 

- http://openqaworker15.qa.suse.cz/tests/276650

#### sle-15-SP5-Qesap-Aws-Byos-x86_64-BuildLATEST_AWS_SLE15_5_BYOS-qesap_aws_sbd_test@64bit 

- http://openqaworker15.qa.suse.cz/tests/276648 :green_circle:

### CODE REVIEW

**Review by lpalovsky — APPROVED** [review]
LGTM

**Comment by a-kpappas** [comment]
Why is the SID not hardcoded to HA0 or something according to https://help.sap.com/docs/SAP_HANA_PLATFORM/2c1988d620e04368aa4103bf26f17727/7672838aa9c44c7ab9d10188531669f3.html ?

**Review by BillAnastasiadis — APPROVED** [review]
LGTM

**Review by alvarocarvajald — APPROVED** [review]
LGTM

**Pull request merged**
