### PR TITLE
Relax gcc package version requirements

### PR DESCRIPTION
**Pull request by mpagot**
SAP HANA needs some gcc packages. Relax the requirement for all sp in SLES15.

Ticket [TEAM-8051](https://jira.suse.com/browse/TEAM-8051)

# Verification:

## Azure
- SLES 12sp5 http://openqaworker15.qa.suse.cz/tests/187306 :heavy_check_mark:
- SLES 15sp4 http://openqaworker15.qa.suse.cz/tests/187305 :heavy_check_mark:
- SLES 15sp5 http://openqaworker15.qa.suse.cz/tests/187307 :heavy_check_mark:

## AWS:
- SLES 12sp5 http://openqaworker15.qa.suse.cz/tests/187308 :heavy_check_mark:
- SLES 15sp4 http://openqaworker15.qa.suse.cz/tests/187303 :heavy_check_mark:
- SLES 15sp5 http://openqaworker15.qa.suse.cz/tests/187311 :heavy_check_mark:

## GCP:
- SLES 12sp5 http://openqaworker15.qa.suse.cz/tests/187310  https://openqaworker15.qa.suse.cz/tests/187767 https://openqaworker15.qa.suse.cz/tests/187770
- SLES 15sp4 http://openqaworker15.qa.suse.cz/tests/187309  https://openqaworker15.qa.suse.cz/tests/187768 http://openqaworker15.qa.suse.cz/tests/187771

### CODE REVIEW

**Comment by hadeskun** [comment]
LGTM

**Review by dzedro — APPROVED** [review]
All I know, it got so complicated because we used old version of `community.general.zypper` which didn't work so well, that was resolved some time ago

**Comment by mpagot** [comment]
> All I know, it got so complicated because we used old version of `community.general.zypper` which didn't work so well, that was resolved some time ago

Indeed I think we update the Ansible later in https://github.com/SUSE/qe-sap-deployment/pull/101

**Review by alvarocarvajald — COMMENTED** [review]
LGTM

**Pull request merged**
