### PR TITLE
Fix hanasr failures on Azure

### PR DESCRIPTION
**Pull request by dzedro**
https://jira.suse.com/browse/TEAM-6887
https://jira.suse.com/browse/TEAM-6893
https://jira.suse.com/browse/TEAM-6894
https://jira.suse.com/browse/TEAM-6897

VR:
https://openqaworker15.qa.suse.cz/tests/58222#step/hana_sr_deployment/252 15sp4
https://openqaworker15.qa.suse.cz/tests/58526#step/hana_sr_deployment/252 15sp4
https://openqaworker15.qa.suse.cz/tests/58223#step/hana_sr_deployment/252 15sp3
https://openqaworker15.qa.suse.cz/tests/58527#step/hana_sr_deployment/252 15sp3
https://openqaworker15.qa.suse.cz/tests/58220#step/hana_sr_deployment/252 15sp2
https://openqaworker15.qa.suse.cz/tests/58528#step/hana_sr_deployment/252 15sp2
https://openqaworker15.qa.suse.cz/tests/58219#step/hana_sr_deployment/252 15sp1
https://openqaworker15.qa.suse.cz/tests/58531#step/hana_sr_deployment/252 15sp1
https://openqaworker15.qa.suse.cz/tests/58218#step/hana_sr_deployment/252 12sp5
https://openqaworker15.qa.suse.cz/tests/58530#step/hana_sr_deployment/252 12sp5

### CODE REVIEW

**Review by lpalovsky — APPROVED** [review]
LGTM

**Review by mpagot — COMMENTED** [review]
LGTM

**Review by mpagot — APPROVED** [review]

**Comment by dzedro** [comment]
I don't have merge rights. Can we merge this or should I do something ?

**Comment by lpalovsky** [comment]
> I don't have merge rights. Can we merge this or should I do something ?

There were 2 approvals. I merged the PR

**Pull request merged**
