### PR TITLE
Remove more Terraform code about Salt provisioner and Bastion

### PR DESCRIPTION
**Pull request by mpagot**
Remove on_destroy
Remove private ssh_key
remove more bastion related variables

Verification:
 - AZURE : http://openqaworker15.qa.suse.cz/tests/133210
 - GCP : http://openqaworker15.qa.suse.cz/tests/133212 failure is a known one due to TEAM-7131  http://openqaworker15.qa.suse.cz/tests/133212/logfile?filename=deploy-qesap_exec_ansible__profile.log.txt
 - AWS : http://openqaworker15.qa.suse.cz/tests/133213 http://openqaworker15.qa.suse.cz/tests/133671 both fails but seems more a failure in Ansible similar to TEAM-7365

### CODE REVIEW

**Review by mr-stringer — APPROVED** [review]
LGTM - get it out of there :)

**Review by mr-stringer — APPROVED** [review]

**Review by alvarocarvajald — APPROVED** [review]
LGTM

**Comment by BillAnastasiadis** [comment]
LGTM

**Review by lpalovsky — APPROVED** [review]
LGTM

**Pull request merged**
