### PR TITLE
Remove unused terraform code

### PR DESCRIPTION
**Pull request by lpalovsky**
This PR removes unused variables and code remaining from old project.
- salt related cluster_ssh_* variables are removed from all providers
- on destroy* related code is removed from all providers

Tested working on both Azure and GCP.

### CODE REVIEW

**Comment by alvarocarvajald** [comment]
Tested in AWS with:
```
git clone https://github.com/lpalovsky/qe-sap-deployment.git
cd qe-sap-deployment/terraform/aws
git checkout Remove_ssh_cluster_keys_variable
cp -i terraform.tfvars.example terraform.tfvars
patch terraform.tfvars ~/tfvars.patch
terraform init
terraform workspace new myworkspace
terraform plan
terraform apply --auto-approve
ssh -i ~/.ssh/id_rsa ec2-user@<X.X.X.X>
terraform destroy --auto-approve
```
Everything seems to be working as expected.

**Review by alvarocarvajald — COMMENTED** [review]
My only suggestion would be to drop those `.*.lock.hcl` files from the PR, otherwise LGTM.

**Comment by lpalovsky** [comment]
> 

Yep I just added nother commit with updated gitignore and removed the lock files from commits.

**Review by alvarocarvajald — APPROVED** [review]
LGTM

**Comment by mr-stringer** [comment]
Looks good 👍

**Pull request merged**
