### PR TITLE
Disable loadbalancer on GCP for non-HA scenarios

### PR DESCRIPTION
**Pull request by lpalovsky**
Load balancer setup is executed by default on GCP regardless of ha being 
enabled. This PR disables load balancer outside of ha scenario and single node 
deployment.

VR: 
single node: https://mordor.suse.cz/tests/5780
cluster:  https://mordor.suse.cz/tests/5778/  (Issue not relevant to terraform)
mr_test (originally affected, fail unrelated):  http://openqaworker15.qa.suse.cz/tests/121245/#

### CODE REVIEW

**Review by dzedro — APPROVED** [review]
I don't understand tf that much, but code make sense and VR passed. :+1:

**Comment by lpalovsky** [comment]
> I don't understand tf that much, but code make sense and VR passed. +1

The issue was that original code would create load balancers even if there was only one host being deployed. Afterwards it would try to assign the non existing second host to the secondary balancer an failing.

**Review by mr-stringer — APPROVED** [review]
LGTM.

I ran the code with and without HA to check that the code behaves as expected. It does. However, the Ansible for creating the volumes is still broken since the deployment name was added to the disk name. It's not related to this change, but it still means that the overall deployment doesn't work.

**Review by lilyeyes — APPROVED** [review]
I don't familiar with this project (https://github.com/SUSE/qe-sap-deployment) but the code changes and VRs really lgtm.

**Comment by lpalovsky** [comment]
> LGTM.
> 
> I ran the code with and without HA to check that the code behaves as expected. It does. However, the Ansible for creating the volumes is still broken since the deployment name was added to the disk name. It's not related to this change, but it still means that the overall deployment doesn't work.

Yes I am aware about that one. Haven't reached that point yet, but will be there soon. I think Michelle was dealing with it so we probably have a Jira ticket in queue already.

**Review by mpagot — APPROVED** [review]
LGTM

**Pull request merged**
