### PR TITLE
Rename internal Ansible value

### PR DESCRIPTION
**Pull request by mpagot**
Rename hana_resource_clone to hana_clone. Because resource is resource and clone is clone of that resource and because all others was named just clone w/o resource.

Code from Jan Kohoutek

Related to ticket : https://jira.suse.com/browse/TEAM-9426

# Verifications

## qesap regression

sle-15-SP6-Qesap-Azure-Payg-x86_64-BuildLATEST_AZURE_SLE15_6_PAYG-qesap_azure_saptune_test
 -  http://openqaworker15.qa.suse.cz/tests/299056 :green_apple: 

sle-15-SP6-Qesap-Aws-Byos-x86_64-BuildLATEST_AWS_SLE15_6_BYOS-qesap_aws_fencing_native_test
 -  http://openqaworker15.qa.suse.cz/tests/299057 :green_apple: 

sle-15-SP5-Qesap-Gcp-Payg-x86_64-BuildLATEST_GCE_SLE15_5_PAYG-qesap_gcp_sapconf_test
 - http://openqaworker15.qa.suse.cz/tests/299058 :green_apple: 

## HanaSR

 - sle-15-SP6-HanaSr-Azure-Byos-x86_64-Build15-SP6_2024-10-04T02:03:19Z-hanasr_azure_test_saptune_msi az_Standard_E4s_v3
 -  http://openqaworker15.qa.suse.cz/tests/299060

 - sle-15-SP6-HanaSr-Aws-Byos-x86_64-Build15-SP6_2024-10-04T02:03:19Z-hanasr_aws_test_fencing_sbd_stop_kill ec2_r4.8xlarge
 -  http://openqaworker15.qa.suse.cz/tests/299059

- sle-15-SP6-HanaSr-Gcp-Payg-x86_64-Build15-SP6_2024-10-04T02:03:19Z-hanasr_gcp_test_fencing_sbd_stop_kill gce_n1_highmem_8 
-  http://openqaworker15.qa.suse.cz/tests/299061

### CODE REVIEW

**Review by jankohoutek — COMMENTED** [review]
change order: to cluster_order:

**Review by jankohoutek — CHANGES_REQUESTED** [review]
PLS also change **order:** to **cluster_order:** as **order** is an internal Ansible variable

**Review by jankohoutek — APPROVED** [review]
LGTM, if you are about to change the rsc_SAPHana var in other MR

**Comment by mpagot** [comment]
> LGTM, if you are about to change the rsc_SAPHana var in other MR

yes, other PR

**Review by jankohoutek — APPROVED** [review]
LGTM

**Review by lpalovsky — APPROVED** [review]
LGTM

**Pull request merged**
